CREATE TABLE GICS (
    primary_sector_code varchar(8) NOT NULL PRIMARY KEY,
    code_name varchar(255),
    code_description varchar(500),
    parent_sector_code varchar(8),
    CONSTRAINT parent_gics_sector_fk FOREIGN KEY (parent_sector_code) REFERENCES GICS (primary_sector_code)
);


INSERT INTO GICS (primary_sector_code, code_name) VALUES ('10', 'Energy');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('1010', 'Energy', '10');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('101010', 'Energy Equipment and Services', '1010');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('10101010', 'Oil and Gas Drilling', '101010', 'Drilling contractors or owners of drilling rigs that contract their services for drilling wells');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('10101020', 'Oil and Gas Equipment and Services', '101010', 'Manufacturers of equipment');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('101020', 'Oil', '1010');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('10102020', 'Oil and Gas Exploration and Production', '101020', 'Companies engaged in the exploration and production of oil and gas not classified elsewhere.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('10102030', 'Oil and Gas Refining and Marketing', '101020', 'Companies engaged in the refining and marketing of oil');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('10102040', 'Oil and Gas Storage and Transportation', '101020', 'Companies engaged in the storage and/or transportation of oil');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('10102050', 'Coal and Consumable Fuels', '101020', 'Companies primarily involved in the production and mining of coal');
INSERT INTO GICS (primary_sector_code, code_name) VALUES ('15', 'Materials');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('1510', 'Materials', '15');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('151010', 'Chemicals', '1510');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('15101010', 'Commodity Chemicals', '151010', 'Companies that primarily produce industrial chemicals and basic chemicals. Including but not limited to plastics');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('15101020', 'Diversified Chemicals', '151010', 'Manufacturers of a diversified range of chemical products not classified in the Industrial Gases');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('15101030', 'Fertilizers and Agricultural Chemicals', '151010', 'Producers of fertilizers');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('15101040', 'Industrial Gases', '151010', 'Manufacturers of industrial gases.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('15101050', 'Specialty Chemicals', '151010', 'Companies that primarily produce high value-added chemicals used in the manufacture of a wide variety of products');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('151020', 'Construction Materials', '1510');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('15102010', 'Construction Materials', '151020', 'Manufacturers of construction materials including sand');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('151030', 'Containers and Packaging', '1510');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('15103010', 'Metal and Glass Containers', '151030', 'Manufacturers of metal');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('15103020', 'Paper Packaging', '151030', 'Manufacturers of paper and cardboard containers and packaging.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('151040', 'Metals and Mining', '1510');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('15104010', 'Aluminum', '151040', 'Producers of aluminum and related products');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('15104020', 'Diversified Metals and Mining', '151040', 'Companies engaged in the diversified production or extraction of metals and minerals not classified elsewhere. Including');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('15104025', 'Copper', '151040', 'Companies involved primarily in copper ore mining.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('15104030', 'Gold', '151040', 'Producers of gold and related products');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('15104040', 'Precious Metals and Minerals', '151040', 'Companies mining precious metals and minerals not classified in the Gold Sub-Industry. Includes companies primarily mining platinum.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('15104045', 'Silver', '151040', 'Companies primarily mining silver. Excludes companies classified in the Gold or Precious Metals and Minerals Sub-Industries.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('15104050', 'Steel', '151040', 'Producers of iron and steel and related products');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('151050', 'Paper and Forest Products', '1510');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('15105010', 'Forest Products', '151050', 'Manufacturers of timber and related wood products. Includes lumber for the building industry.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('15105020', 'Paper Products', '151050', 'Manufacturers of all grades of paper. Excludes companies specializing in paper packaging classified in the Paper Packaging Sub-Industry.');
INSERT INTO GICS (primary_sector_code, code_name) VALUES ('20', 'Industrials');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('2010', 'Capital Goods', '20');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('201010', 'Aerospace and Defense', '2010');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20101010', 'Aerospace and Defense', '201010', 'Manufacturers of civil or military aerospace and defense equipment');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('201020', 'Building Products', '2010');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20102010', 'Building Products', '201020', 'Manufacturers of building components and home improvement products and equipment. Excludes lumber and plywood classified under Forest Products and cement and other materials classified in the Construction Materials Sub-Industry.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('201030', 'Construction and Engineering', '2010');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20103010', 'Construction and Engineering', '201030', 'Companies engaged in primarily non-residential construction. Includes civil engineering companies and large-scale contractors. Excludes companies classified in the Homebuilding Sub-Industry.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('201040', 'Electrical Equipment', '2010');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20104010', 'Electrical Components and Equipment', '201040', 'Companies that produce electric cables and wires');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20104020', 'Heavy Electrical Equipment', '201040', 'Manufacturers of power-generating equipment and other heavy electrical equipment');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('201050', 'Industrial Conglomerates', '2010');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20105010', 'Industrial Conglomerates', '201050', 'Diversified industrial companies with business activities in three or more sectors');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('201060', 'Machinery', '2010');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20106010', 'Construction Machinery and Heavy Trucks', '201060', 'Manufacturers of heavy duty trucks');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20106015', 'Agricultural and Farm Machinery', '201060', 'Companies manufacturing agricultural machinery');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20106020', 'Industrial Machinery', '201060', 'Manufacturers of industrial machinery and industrial components. Includes companies that manufacture presses');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('201070', 'Trading Companies and Distributors', '2010');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20107010', 'Trading Companies and Distributors', '201070', 'Trading companies and other distributors of industrial equipment and products.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('2020', 'Commercial  and Professional Services', '20');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('202010', 'Commercial Services and Supplies', '2020');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20201010', 'Commercial Printing', '202010', 'Companies providing commercial printing services. Includes printers primarily serving the media industry.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20201050', 'Environmental and Facilities Services', '202010', 'Companies providing environmental and facilities maintenance services. Includes waste management');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20201060', 'Office Services and Supplies', '202010', 'Providers of office services and manufacturers of office supplies and equipment not classified elsewhere.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20201070', 'Diversified Support Services', '202010', 'Companies primarily providing labor oriented support services to businesses and governments.  Includes commercial cleaning services');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20201080', 'Security and Alarm Services', '202010', 'Companies providing security and protection services to business and governments. Includes companies providing services such as correctional facilities');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('202020', 'Professional Services', '2020');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20202010', 'Human Resource and Employment Services', '202020', 'Companies providing business support services relating to human capital management. Includes employment agencies');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20202020', 'Research and Consulting Services', '202020', 'Companies primarily providing research and consulting services to businesses and governments not classified elsewhere.  Includes companies involved in management consulting services');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('2030', 'Transportation', '20');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('203010', 'Air Freight and Logistics', '2030');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20301010', 'Air Freight and Logistics', '203010', 'Companies providing air freight transportation');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('203020', 'Airlines', '2030');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20302010', 'Airlines', '203020', 'Companies providing primarily passenger air transportation.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('203030', 'Marine', '2030');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20303010', 'Marine', '203030', 'Companies providing goods or passenger maritime transportation. Excludes cruise-ships classified in the Hotels');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('203040', 'Road and Rail', '2030');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20304010', 'Railroads', '203040', 'Companies providing primarily goods and passenger rail  transportation.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20304020', 'Trucking', '203040', 'Companies providing primarily goods and passenger land transportation. Includes vehicle rental and taxi companies.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('203050', 'Transportation Infrastructure', '2030');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20305010', 'Airport Services', '203050', 'Operators of airports and companies providing related services.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20305020', 'Highways and Railtracks', '203050', 'Owners and operators of roads');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('20305030', 'Marine Ports and Services', '203050', 'Owners and operators of marine ports and related services.');
INSERT INTO GICS (primary_sector_code, code_name) VALUES ('25', 'Consumer Discretionary');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('2510', 'Automobiles and Components', '25');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('251010', 'Auto Components', '2510');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25101010', 'Auto Parts and Equipment', '251010', 'Manufacturers of parts and accessories for  automobiles and motorcycles. Excludes companies classified in the Tires and Rubber Sub-Industry.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25101020', 'Tires and Rubber', '251010', 'Manufacturers of tires and rubber.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('251020', 'Automobiles', '2510');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25102010', 'Automobile Manufacturers', '251020', 'Companies that produce mainly passenger automobiles and light trucks. Excludes companies producing mainly motorcycles and three-wheelers classified in the Motorcycle Manufacturers Sub-Industry and heavy duty trucks classified in the Construction Machinery and Heavy Trucks Sub-Industry.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25102020', 'Motorcycle Manufacturers', '251020', 'Companies that produce motorcycles');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('2520', 'Consumer Durables and Apparel', '25');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('252010', 'Household Durables', '2520');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25201010', 'Consumer Electronics', '252010', 'Manufacturers of consumer electronics products including TVs');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25201020', 'Home Furnishings', '252010', 'Manufacturers of soft home furnishings or furniture');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25201030', 'Homebuilding', '252010', 'Residential construction companies. Includes manufacturers of prefabricated houses and semi-fixed manufactured homes.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25201040', 'Household Appliances', '252010', 'Manufacturers of electric household appliances and related products.  Includes manufacturers of power and hand tools');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25201050', 'Housewares and Specialties', '252010', 'Manufacturers of durable household products');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('252020', 'Leisure Products', '2520');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25202010', 'Leisure Products', '252020', 'Manufacturers of leisure products and equipment including sports equipment');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('252030', 'Textiles', '2520');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25203020', 'Footwear', '252030', 'Manufacturers of footwear. Includes sport and leather shoes.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25203030', 'Textiles', '252030', 'Manufacturers of textile and related products not classified in the Apparel');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('2530', 'Consumer Services', '25');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('253010', 'Hotels', '2530');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25301020', 'Hotels', '253010', 'Owners and operators of hotels');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25301030', 'Leisure Facilities', '253010', 'Owners and operators of leisure facilities');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25301040', 'Restaurants', '253010', 'Owners and operators of restaurants');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('253020', 'Diversified Consumer Services', '2530');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25302010', 'Education Services', '253020', 'Companies providing educational services');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25302020', 'Specialized Consumer Services', '253020', 'Companies providing consumer services not classified elsewhere.  Includes residential services');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('2540', 'Media', '25');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('254010', 'Media', '2540');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25401010', 'Advertising', '254010', 'Companies providing advertising');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25401020', 'Broadcasting', '254010', 'Owners and operators of television or radio broadcasting systems');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25401025', 'Cable and Satellite', '254010', 'Providers of cable or satellite television services. Includes cable networks and program distribution.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25401030', 'Movies and Entertainment', '254010', 'Companies that engage in producing and selling entertainment products and services');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25401040', 'Publishing', '254010', 'Publishers of newspapers');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('2550', 'Retailing', '25');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('255010', 'Distributors', '2550');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25501010', 'Distributors', '255010', 'Distributors and wholesalers of general merchandise not classified elsewhere. Includes vehicle distributors.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('255020', 'Internet and Direct Marketing Retail', '2550');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25502020', 'Internet and Direct Marketing Retail', '255020', 'Companies  providing  retail  services  primarily  on  the Internet');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('255030', 'Multiline Retail', '2550');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25503010', 'Department Stores', '255030', 'Owners and operators of department stores.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25503020', 'General Merchandise Stores', '255030', 'Owners and operators of stores offering diversified general merchandise. Excludes hypermarkets and large-scale super centers classified in the Hypermarkets and Super Centers Sub-Industry.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('255040', 'Specialty Retail', '2550');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25504010', 'Apparel Retail', '255040', 'Retailers specialized mainly in apparel and accessories.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25504020', 'Computer and Electronics Retail', '255040', 'Owners and operators of consumer electronics');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25504030', 'Home Improvement Retail', '255040', 'Owners and operators of home and garden improvement retail stores. Includes stores offering building materials and supplies.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25504040', 'Specialty Stores', '255040', 'Owners and operators of specialty retail stores not classified elsewhere. Includes jewelry stores');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25504050', 'Automotive Retail', '255040', 'Owners and operators of stores specializing in automotive retail.  Includes auto dealers');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('25504060', 'Homefurnishing Retail', '255040', 'Owners and operators of furniture and home furnishings retail stores.  Includes residential furniture');
INSERT INTO GICS (primary_sector_code, code_name) VALUES ('30', 'Consumer Staples');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('3010', 'Food and Staples Retailing', '30');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('301010', 'Food and Staples Retailing', '3010');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('30101010', 'Drug Retail', '301010', 'Owners and operators of primarily drug retail stores and pharmacies.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('30101020', 'Food Distributors', '301010', 'Distributors of food products to other companies and not directly to the consumer.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('30101030', 'Food Retail', '301010', 'Owners and operators of primarily food retail stores.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('30101040', 'Hypermarkets and Super Centers', '301010', 'Owners and operators of hypermarkets and super centers selling food and a wide-range of consumer staple products.  Excludes Food and Drug Retailers classified in the Food Retail and Drug Retail Sub-Industries');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('3020', 'Food', '30');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('30201020', 'Distillers and Vintners', '301010', 'Distillers');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('30201030', 'Soft Drinks', '301010', 'Producers of non-alcoholic beverages including mineral waters. Excludes producers of milk classified in the Packaged Foods Sub-Industry.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('302020', 'Food Products', '3020');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('30202010', 'Agricultural Products', '302020', 'Producers of agricultural products. Includes crop growers');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('30202030', 'Packaged Foods and Meats', '302020', 'Producers of packaged foods including dairy products');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('302030', 'Tobacco', '3020');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('30203010', 'Tobacco', '302030', 'Manufacturers of cigarettes and other tobacco products.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('3030', 'Household and Personal Products', '30');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('303010', 'Household Products', '3030');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('30301010', 'Household Products', '303010', 'Producers of non-durable household products');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('303020', 'Personal Products', '3030');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('30302010', 'Personal Products', '303020', 'Manufacturers of personal and beauty care products');
INSERT INTO GICS (primary_sector_code, code_name) VALUES ('35', 'Health Care');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('3510', 'Health Care Equipment and Services', '35');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('351010', 'Health Care Equipment and Supplies', '3510');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('35101010', 'Health Care Equipment', '351010', 'Manufacturers of health care equipment and devices. Includes medical instruments');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('35101020', 'Health Care Supplies', '351010', 'Manufacturers of health care supplies and medical products not classified elsewhere. Includes eye care products');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('351020', 'Health Care Providers and Services', '3510');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('35102010', 'Health Care Distributors', '351020', 'Distributors and wholesalers of health care products not classified elsewhere.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('35102015', 'Health Care  Services', '351020', 'Providers of patient health care services not classified elsewhere. Includes dialysis centers');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('35102020', 'Health Care Facilities', '351020', 'Owners and operators of health care facilities');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('35102030', 'Managed Health Care', '351020', 'Owners and operators of Health Maintenance Organizations (HMOs) and other managed plans.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('351030', 'Health Care Technology', '3510');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('35103010', 'Health Care Technology', '351030', 'Companies providing information technology services primarily to health care providers.  Includes companies providing application');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('3520', 'Pharmaceuticals', '35');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('352020', 'Pharmaceuticals', '3520');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('35202010', 'Pharmaceuticals', '352020', 'Companies engaged in the research');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('352030', 'Life Sciences Tools and Services', '3520');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('35203010', 'Life Sciences Tools and Services', '352030', 'Companies enabling the drug discovery');
INSERT INTO GICS (primary_sector_code, code_name) VALUES ('40', 'Financials');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('4010', 'Banks', '40');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('401010', 'Banks', '4010');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('40101010', 'Diversified Banks', '401010', 'Large');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('40101015', 'Regional Banks', '401010', 'Commercial banks whose businesses are derived primarily from conventional banking operations and have significant business activity in retail banking and small and medium corporate lending. Regional banks tend to operate in limited geographic regions. Excludes companies classified in the Diversified Banks and Thrifts and Mortgage Banks sub-industries. Also excludes investment banks classified in the Investment Banking and Brokerage Sub-Industry.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('401020', 'Thrifts and Mortgage Finance', '4010');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('40102010', 'Thrifts and Mortgage Finance', '401020', 'Financial institutions providing mortgage and mortgage related services.  These include financial institutions whose assets are primarily mortgage related');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('4020', 'Diversified Financials', '40');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('402010', 'Diversified Financial Services', '4020');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('40201020', 'Other Diversified Financial Services', '402010', 'Providers of a diverse range of financial services and/or with some interest in a wide range of financial services including banking');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('40201030', 'Multi-Sector Holdings', '402010', 'A company with significantly diversified holdings across three or more sectors');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('40201040', 'Specialized Finance', '402010', 'Providers  of  specialized  financial  services  not  classified  elsewhere. Companies  in  this  sub-industry  derive  a  majority  of  revenue  from  one  specialized  line  of  business.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('402020', 'Consumer Finance', '4020');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('40202010', 'Consumer Finance', '402020', 'Providers of consumer finance services');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('402030', 'Capital Markets', '4020');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('40203010', 'Asset Management and Custody Banks', '402030', 'Financial institutions primarily engaged in investment management and/or related custody and securities fee-based services. Includes companies operating mutual funds');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('40203020', 'Investment Banking and Brokerage', '402030', 'Financial institutions primarily engaged in investment banking and brokerage services');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('40203030', 'Diversified Capital Markets', '402030', 'Financial institutions primarily engaged in diversified capital markets activities');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('40203040', 'Financial Exchanges and Data', '402030', 'Financial  exchanges  for  securities');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('402040', 'Mortgage Real Estate Investment', '4020');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('4030', 'Insurance', '40');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('403010', 'Insurance', '4030');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('40301010', 'Insurance Brokers', '403010', 'Insurance and reinsurance brokerage firms.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('40301020', 'Life and Health Insurance', '403010', 'Companies providing primarily life');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('40301030', 'Multi-line Insurance', '403010', 'Insurance companies with diversified interests in life');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('40301040', 'Property and Casualty Insurance', '403010', 'Companies providing primarily property and casualty insurance.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('40301050', 'Reinsurance', '403010', 'Companies providing primarily reinsurance.');
INSERT INTO GICS (primary_sector_code, code_name) VALUES ('45', 'Information Technology');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('4510', 'Software and Services', '45');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('451010', 'Internet Software and Services', '4510');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('45101010', 'Internet Software and Services', '451010', 'Companies developing and marketing internet software and/or providing internet services including online databases and interactive services');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('451020', 'IT Services', '4510');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('45102010', 'IT Consulting and Other Services', '451020', 'Providers of information technology and systems integration services not classified in the Data Processing and Outsourced Services or Internet Software and Services Sub-Industries.  Includes information technology consulting and information management services.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('45102020', 'Data Processing and Outsourced Services', '451020', 'Providers of commercial electronic data processing and/or business process outsourcing services.  Includes companies that provide services for back-office automation.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('451030', 'Software', '4510');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('45103010', 'Application Software', '451030', 'Companies engaged in developing and producing software designed for specialized applications for the business or consumer market. Includes enterprise and technical software. Excludes companies classified in the Home Entertainment Software Sub-Industry. Also excludes companies producing systems or database management software classified in the Systems Software Sub-Industry.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('45103020', 'Systems Software', '451030', 'Companies engaged in developing and producing systems and database management software.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('45103030', 'Home Entertainment Software', '451030', 'Manufacturers of home entertainment software and educational software used primarily in the home.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('4520', 'Technology Hardware and Equipment', '45');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('452010', 'Communications Equipment', '4520');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('45201020', 'Communications Equipment', '452010', 'Manufacturers of communication equipment and products');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('452020', 'Technology Hardware', '4520');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('452030', 'Electronic Equipment', '4520');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('45203015', 'Electronic Components', '452030', 'Manufacturers of electronic components. Includes electronic components');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('45203020', 'Electronic Manufacturing Services', '452030', 'Producers of electronic equipment mainly for the OEM (Original Equipment Manufacturers) markets.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('45203030', 'Technology Distributors', '452030', 'Distributors of technology hardware and equipment. Includes distributors of communications equipment');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('4530', 'Semiconductors and Semiconductor Equipment', '45');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('453010', 'Semiconductors and Semiconductor Equipment', '4530');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('45301010', 'Semiconductor Equipment', '453010', 'Manufacturers of semiconductor equipment');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('45301020', 'Semiconductors', '453010', 'Manufacturers of semiconductors and related products');
INSERT INTO GICS (primary_sector_code, code_name) VALUES ('50', 'Telecommunication Services');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('5010', 'Telecommunication Services', '50');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('501010', 'Diversified Telecommunication Services', '5010');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('50101010', 'Alternative Carriers', '501010', 'Providers of communications and high-density data transmission services primarily through a high bandwidth/fiber-optic cable network.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('50101020', 'Integrated Telecommunication Services', '501010', 'Operators of primarily fixed-line telecommunications networks and companies providing both wireless and fixed-line telecommunications services not classified elsewhere.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('501020', 'Wireless Telecommunication Services', '5010');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('50102010', 'Wireless Telecommunication Services', '501020', 'Providers of primarily cellular or wireless telecommunication services');
INSERT INTO GICS (primary_sector_code, code_name) VALUES ('55', 'Utilities');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('5510', 'Utilities', '55');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('551010', 'Electric Utilities', '5510');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('55101010', 'Electric Utilities', '551010', 'Companies that produce or distribute electricity. Includes both nuclear and non-nuclear facilities.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('551020', 'Gas Utilities', '5510');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('55102010', 'Gas Utilities', '551020', 'Companies whose main charter is to distribute and transmit natural and manufactured gas. Excludes companies primarily involved in gas exploration or production classified in the Oil and Gas Exploration and Production Sub-Industry.   Also excludes diversified midstream natural gas companies classified in the Oil and Gas Storage and Transportation Sub-Industry.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('551030', 'Multi-Utilities', '5510');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('55103010', 'Multi-Utilities', '551030', 'Utility companies with significantly diversified activities in addition to core Electric Utility');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('551040', 'Water Utilities', '5510');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('55104010', 'Water Utilities', '551040', 'Companies that purchase and redistribute water to the end-consumer. Includes large-scale water treatment systems.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('551050', 'Independent Power and Renewable Electricity Producers', '5510');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('55105010', 'Independent Power Producers and Energy Traders', '551050', 'Companies that operate as Independent Power Producers (IPPs)');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('55105020', 'Renewable Electricity', '551050', 'Companies that engage in the generation and distribution of electricity using renewable sources');
INSERT INTO GICS (primary_sector_code, code_name) VALUES ('60', 'Real Estate');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('6010', 'Real Estate', '60');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('601010', 'Equity Real Estate', '6010');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('60101020', 'Industrial REITs', '601010', 'Companies or Trusts engaged in the acquisition');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('60101030', 'Hotel and Resort REITs', '601010', 'Companies or Trusts engaged in the acquisition');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('60101040', 'Office REITs', '601010', 'Companies or Trusts engaged in the acquisition');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('60101050', 'Health Care REITs', '601010', 'Companies or Trusts engaged in the acquisition');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('60101060', 'Residential REITs', '601010', 'Companies or Trusts engaged in the acquisition');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('60101070', 'Retail REITs', '601010', 'Companies or Trusts engaged in the acquisition');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('60101080', 'Specialized REITs', '601010', 'Companies or Trusts engaged in the acquisition');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code) VALUES ('601020', 'Real Estate Management and Development', '6010');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('60102010', 'Diversified Real Estate Activities', '601020', 'Companies engaged in a diverse spectrum of real estate activities including real estate development and sales');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('60102020', 'Real Estate Operating Companies', '601020', 'Companies engaged in operating real estate properties for the purpose of leasing and management.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('60102030', 'Real Estate Development', '601020', 'Companies that develop real estate and sell the properties after development. Excludes companies classified in the Homebuilding Sub-Industry.');
INSERT INTO GICS (primary_sector_code, code_name, parent_sector_code, code_description) VALUES ('60102040', 'Real Estate Services', '601020', 'Real estate service providers such as real estate agents');
