/*Insert 10 courses into course
CREATE TABLE course(
    c_code NUMBER GENERATED by default on null as IDENTITY PRIMARY KEY,
    title varchar(255) NOT NULL,
    training_level varchar(12), -- Beginner, Intermediate, Advanced
    description varchar(255),
    status varchar(1) NOT NULL, -- A: Active, E: Expired
    retail_price number(10,2),
    train_type varchar(255) NOT NULL -- University, Training Company, Online Course, Non-Profit
);
*/
DELETE FROM course; 
INSERT into course (title, training_level, description, status, retail_price, train_type) 
    VALUES('Data Models and Database Systems','Beginner','Methods, structures, and 
    algorithms used for the organization, representation, and manipulation of large data bases; 
    design and implementation of data base management systems','A',1770.80,'University-Traditional');
INSERT into course (title, training_level, description, status, retail_price, train_type) 
    VALUES('The Ultimate MySQL Bootcamp: Go from SQL Beginner to Expert','Intermediate',
    'Become an In-demand SQL Master by creating complex databases and building reports through 
    real-world projects','A',199.99,'Online Course');
INSERT into course (title, training_level, description, status, retail_price, train_type) 
    VALUES('Python for Financial Analysis and Algorithmic Trading','Intermediate','Learn numpy, 
    pandas, matplotlib, quantopian, finance, and more for algorithmic trading with Python!','A',
    194.99,'Online course');
INSERT into course (title, training_level, description, status, retail_price, train_type) 
    VALUES('CompTIA A+ Certification','Beginner','Acquire the essential skills and information you 
    will need to install, configure, optimize, troubleshoot, repair, upgrade, and perform preventive 
    maintenance on PCs, digital devices, and operating systems.','A',2475.00,'Training company');
INSERT into course (title, training_level, description, status, retail_price, train_type) 
    VALUES('IT Fundamentals for Business Professionals','Intermediate','Learn the basic concepts of 
    Information Systems and their application and the terminology used in IT to advance your career',
    'A',337.50,'University-Online');
INSERT into course (title, training_level, description, status, retail_price, train_type) 
    VALUES('Enabling Technologies for Data Science and Analytics: The Internet of Things','Beginner',
    'Discover the relationship between Big Data and the Internet of Things (IoT)','A',0.00,'Online course');
INSERT into course (title, training_level, description, status, retail_price, train_type) 
    VALUES('Project Management for Senior Managers','Advanced','This one-day course introduces the senior 
    managers, department managers, and other key stakeholders to the principles and processes of project management',
    'A',599.00,'Training Company');
INSERT into course (title, training_level, description, status, retail_price, train_type) 
    VALUES('Machine Learning for Trading','Advanced','This course introduces students to the real world challenges 
    of implementing machine learning based trading strategies including the algorithmic steps from information gathering
    to market orders','A',811.00,'University-Online');
INSERT into course (title, training_level, description, status, retail_price, train_type) 
    VALUES('Critical Thinking and Problem-Solving','Advanced','The most successful professionals are able to assess the 
    environment, analyze a situation, design a solution, and ultimately win in a competitive scenario','A',0.00,'Online 
    Course');
INSERT into course (title, training_level, description, status, retail_price, train_type) 
    VALUES('Mandarin Chinese for Business','Intermediate','Learn common Mandarin Chinese business phrases and 
    understand Chinese culture so you can communicate professionally in the largest market in the world','A',0.00,
    'Online Course');
/*Test course*/
select * from course order by c_code;